group:
  repos: |
    sixtema-marketing/dsix2025@sixtema
  files:
    - source: dsix2025/tokens/global-lib/
    - source: dsix2025/tokens/semantic-lib/
    - source: dsix2025/tokens/theme-lib/
      replace: true
