group:
  repos: |
    usuario/repo1
    usuario/repo2
    usuario/repo3
  files:
    - source: dsix2025/tokens/global-lib/
    - source: dsix2025/tokens/semantic-lib/
    - source: dsix2025/tokens/theme-lib/
      replace: true
