name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Repo File Sync Action
        uses: BetaHuhn/repo-file-sync-action@v1.17.21
        with:
          GH_PAT: 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
          PR_LABELS: |
                Brands Json and Directory Sync
          SKIP_PR: true
